test:stable:
  script: &test_script
  - rustc --version && cargo --version
  - cargo test --verbose
  image: rust

test:1.56:
  script: *test_script
  image: rust:1.56

test:nightly:
  script: *test_script
  image: rustlang/rust:nightly
