test:stable:
  script: &test_script
  - rustc --version && cargo --version
  - cargo test --verbose
  image: rust

test:1.49:
  script: *test_script
  image: rust:1.49

test:beta:
  script: *test_script
  image: liuchong/rustup:beta

test:nightly:
  script: *test_script
  image: rustlang/rust:nightly

test:nightly:const-generics:
  script:
  - rustc --version && cargo --version
  - cargo test --all-features --verbose
  image: rustlang/rust:nightly
