[package]
name = "array-macro"
version = "1.0.2"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
repository = "https://github.com/xfix/array-macro"
license = "MIT/Apache-2.0"
description = "Array multiple elements constructor syntax"
keywords = ["data-structure", "no_std", "array"]
categories = ["data-structures", "no-std"]
documentation = "https://docs.rs/array-macro"

[badges]
travis-ci = { repository = "xfix/array-macro" }
